return {
  lspkinds = {
    Namespace = "󰌗",
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰆧",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󱓻",
    File = "󰈚",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "󰊄",
    Table = "",
    Object = "󰅩",
    Tag = "",
    Array = "[]",
    Boolean = "",
    Number = "",
    Null = "󰟢",
    Supermaven = "",
    String = "󰉿",
    Calendar = "",
    Watch = "󰥔",
    Package = "",
    Copilot = "",
    Codeium = "",
    TabNine = "",
    BladeNav = "",
  },
  colors = {
    base00 = "#0f0f0f", -- nền chính
    base01 = "#1a1a1a", -- nền phụ
    base02 = "#222222", -- block
    base03 = "#5a5a5a", -- comment
    base04 = "#a0a0a0", -- text phụ
    base05 = "#d4d4d4", -- text chính
    base06 = "#e5e5e5",
    base07 = "#ffffff",
    base08 = "#d16969", -- red
    base09 = "#d7ba7d", -- orange
    base0A = "#4ec9b0", -- teal
    base0B = "#b5cea8", -- green
    base0C = "#9cdcfe", -- cyan
    base0D = "#569cd6", -- blue
    base0E = "#c586c0", -- purple
    base0F = "#ce9178", -- brown
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  icons_vscode = {
    File = " ",
    Module = " ",
    Namespace = " ",
    Package = " ",
    Class = " ",
    Method = " ",
    Property = " ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = " ",
    Variable = " ",
    Constant = " ",
    String = " ",
    Number = " ",
    Boolean = " ",
    Array = " ",
    Object = " ",
    Key = " ",
    Null = " ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
  diagnostics = {
    Error = "E ",
    Warn = "W ",
    Hint = "H ",
    Info = "I ",
  },
}
