return {
  lspkinds = {
    Namespace = "󰌗",
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰆧",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󱓻",
    File = "󰈚",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "󰊄",
    Table = "",
    Object = "󰅩",
    Tag = "",
    Array = "[]",
    Boolean = "",
    Number = "",
    Null = "󰟢",
    Supermaven = "",
    String = "󰉿",
    Calendar = "",
    Watch = "󰥔",
    Package = "",
    Copilot = "",
    Codeium = "",
    TabNine = "",
    BladeNav = "",
  },
  colors = {
    base00 = "#1f1f1f", -- editor background
    base01 = "#181818", -- sidebar / panel
    base02 = "#2a2d2e", -- selection / block
    base03 = "#6a9955", -- comment
    base04 = "#808080", -- subtle text
    base05 = "#d5d5d5", -- main text
    base06 = "#e5e5e5", -- lighter text
    base07 = "#ffffff", -- white

    base08 = "#d16969", -- red (errors)
    base09 = "#d7ba7d", -- orange (numbers)
    base0A = "#dcdcaa", -- yellow (constants)
    base0B = "#b5cea8", -- green (strings)
    base0C = "#4ec9b0", -- cyan (types)
    base0D = "#569cd6", -- blue (keywords)
    base0E = "#c586c0", -- purple (classes/functions)
    base0F = "#ce9178", -- brown (parameters, accents)
  },
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  icons_vscode = {
    File = " ",
    Module = " ",
    Namespace = " ",
    Package = " ",
    Class = " ",
    Method = " ",
    Property = " ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = " ",
    Variable = " ",
    Constant = " ",
    String = " ",
    Number = " ",
    Boolean = " ",
    Array = " ",
    Object = " ",
    Key = " ",
    Null = " ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
  diagnostics = {
    Error = "E ",
    Warn = "W ",
    Hint = "H ",
    Info = "I ",
  },
}
